### PR TITLE
Updated api to verstion 3

### PR DESCRIPTION
**Pull request by spankratov**

### CODE REVIEW

**Comment by lexa** [comment]
Thank you for creating a PR.

Unfortunately it cannot be merged straight away due to the conflicts. Could you please rebase it ?

**Comment by lexa** [comment]
> As for an interest in working on addon, I thought that the addon was abandoned and indeed had plans for working on it, but right now I'm not sure whether I would have time for that.

Any help will be appreciated.

**Comment by spankratov** [comment]
I rebased the PR. It seems though that all changes I made in my fork was already introduced in this repository :)

**Comment by lexa** [comment]
Thank you for your participation, keep it up.

If you have any suggestions, or an even better PR. I will gladly accept them.

**Pull request merged**
